name: ubuntu build
run-name: build runner on ubuntu ðŸš€

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    paths:
      - 'cmake/*'
      - 'include/*'
      - 'src/*'
      - 'tests/*'
      - 'CMakeLists.txt'
      - 'scripts/*'
      - 'setup.py'
      - '.github/workflows/ubuntu-build.yaml'

jobs:
  build-amd-ubuntu:
    strategy:
      matrix:
        os: ["16.04", "18.04", "20.04", "22.04"]
    runs-on: ubuntu-latest
    container:
      image: docker://ubuntu:${{ matrix.os }}
      options: --volume ${{ github.workspace }}:/workspace/${{ github.repository }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          apt update
          apt install -y python3-dev git pkg-config g++ cmake libtinyxml2-dev
      - name: Build
        run: |
          bash -c "cd /workspace/${{ github.repository }} && python3 setup.py && source install/setup.bash && ./scripts/build.sh"
      - name: Test
        run: |
          bash -c "cd /workspace/${{ github.repository }} && source install/setup.bash && ./scripts/run_tests.sh"

